### ISSUE TITLE
Add repo project topics

### ISSUE THREAD

**Issue by jf990** [Esri/nearby-android#66]
To have this project appear in searches from esri.github.io, please add these topics:
- runtime
- arcgis
- android

**Comment by mikewilburn** [comment]
@jf990 do you mean adding these as topics?

**Comment by jf990** [comment]
@mikewilburn ugh, yes, sorry for that. As topics so it comes up in the search.
Thanks!

**Comment by mikewilburn** [comment]
This has been done.
