### ISSUE TITLE
How can I navigate from current place to destination ?

### ISSUE THREAD

**Issue by alexd555** [Esri/nearby-android#71]
How can I navigate from current place to destination ?
How can I choose radius of places ?
Why don't you choose to use with Google Map ?
Thanks,
Alex
@zinfin

**Comment by fallsdownhill** [comment]
>How can I navigate from current place to destination ?
You can read more about how the routing was done for the app by going to the "Routing" section here: https://developers.arcgis.com/example-apps/nearby-android/ and exploring some of the related links.

>How can I choose radius of places ?
The geocoding is kicked off here: https://github.com/Esri/nearby-android/blob/master/nearby-app/src/main/java/com/esri/android/nearbyplaces/places/PlacesPresenter.java#L98
You can set a radius through the parameters, and there are also other places in the place filtering code where you can set a custom extent to show results. There's nothing exposed currently in the app to let you change it through the UI

>Why don't you choose to use with Google Map ?
This app is built with https://developers.arcgis.com/android/latest/ and is meant to showcase the Esri platform and associated SDKs.
