### ISSUE TITLE
Location cannot be determined

### ISSUE THREAD

**Issue by alexd555** [Esri/nearby-android#72]
Hi,
I installed this app on Samsung galaxy s5 and when I run this app then I get "Location cannot be determined"
My GPS is enabled and I have internet connection.
When I go to google maps , look on my current location and then return to this app then it is OK.
How can I fix it ?

**Comment by ramasCoder** [comment]
Is it occurring on other mobile phones as well ?

**Comment by alexd555** [comment]
Yes. I also run on Nexus 4. I don't get a message "Location cannot be determined" but I also don't see any thing. After that I run google map and then return back to this app, then All is Ok.

**Comment by jf990** [comment]
@alexd555 do you have COARSE and FINE location enabled in android manifest?

https://github.com/Esri/nearby-android/blob/master/nearby-app/src/main/AndroidManifest.xml

and did you accept the permissions request for the app? if you reject the permissions request you will get this issue.

**Comment by alexd555** [comment]
I did clone from the repository. That means that I have this configuration. @jf990

**Comment by fallsdownhill** [comment]
I wasn't able to reproduce this on devices I have currently (Samsung S6 and a Moto X). I'm not sure what could be causing problems on your devices. It's on my todo list to rework the permission handling soon which may end up fixing it.

**Comment by fallsdownhill** [comment]
This should be fixed with updates to target API level and some tweaks to the permission handling code put in place here: https://github.com/Esri/nearby-android/pull/83
