### ISSUE TITLE
Filtering

### ISSUE THREAD

**Issue by alexd555** [Esri/nearby-android#74]
How can I add objects to maps ?
For example, I want add the location of people and do filtering.

**Comment by fallsdownhill** [comment]
A good place to get started with that would be this guide series: https://developers.arcgis.com/android/latest/guide/add-graphics-overlays-to-your-app.htm

There is also associated sample code. For example if you just wanted to display a graphic at a location: https://developers.arcgis.com/android/latest/sample-code/simple-marker-symbol.htm
