### ISSUE TITLE
Bottom sheet appears and disappears when identifying some records

### ISSUE THREAD

**Issue by mikewilburn** [Esri/nearby-android#77]
A small percentage of the time, when identifying search results by tapping their icon on the map, the bottom sheet appears but then immediately disappears for that record.
From my experience, this seems to occur around 30% of the time.
![bottom-sheet-issues](https://user-images.githubusercontent.com/25207711/51274162-4cb74480-1983-11e9-8362-a150dc336cea.gif)

This also occurs when trying to navigate to a map point by clicking a result from the list view:
![bottom-sheet-from-list](https://user-images.githubusercontent.com/25207711/51274272-96a02a80-1983-11e9-87f4-a9ec93e72b57.gif)

**Comment by fallsdownhill** [comment]
Fixed with above PR.
