### ISSUE TITLE
Permissions Snackbar is always shown

### ISSUE THREAD

**Issue by LDuncAndroid** [Esri/nearby-android#80]
https://github.com/Esri/nearby-android/blob/135a71dbc57b192eaa1f0b8d7f472030d7338cb5/nearby-app/src/main/java/com/esri/android/nearbyplaces/places/PlacesActivity.java#L216-L219

This block is always fired when requesting permissions, even if permissions have been granted. It might be better to check if the permissions have been granted before calling the `requestPermissions()` method.

**Comment by fallsdownhill** [comment]
Fixed with above PR.
