### ISSUE TITLE
java.lang.NullPointerException thrown when places empty

### ISSUE THREAD

**Issue by LDuncAndroid** [Esri/nearby-android#81]
https://github.com/Esri/nearby-android/blob/135a71dbc57b192eaa1f0b8d7f472030d7338cb5/nearby-app/src/main/java/com/esri/android/nearbyplaces/data/LocationService.java#L285

You can repro this by following these steps:

1. Launch app
2. Tapping Filter item
3. Tapping "Apply" on the dialog
4. Tapping outside progress dialog to cancel
5. Tapping Map item

**Comment by fallsdownhill** [comment]
Fixed with above PR.
