### ISSUE TITLE
Migrate to Update 6

### ISSUE THREAD

**Issue by esreli** [Esri/nearby-android#87]
Minimum requirement:

- [x] 1. Ensure source code compiles & runs.
- [x] 2. Fix all new warnings & errors.
- [x] 3. There is no test design document, play with the app a bit and ensure it operates as you might expect!

**Comment by puneet-pdx** [comment]
@esreli the PR has been merged to master and I have published the release. Can you verify?

**Comment by esreli** [comment]
Thank you @puneet-pdx, the repo looks good as does the release. Assuming testing for U6 was performed by the android team, I verify this issue.
